#!/usr/bin/env python3
"""Map screenshot-visible VictronConnect UI fields to static QML path candidates.

Input is generated by scripts/extract-qmlcache-strings.py. The output is a
reproducible candidate table, not a runtime-confirmed BLE mapping.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

PROPERTY_MODULES = ["VBusItemsSolarCharger", "PageSolarCharger", "PageSolarChargerHistory", "SolarChargerHistoryGraphFullSceen", "TrendsSolarCharger", "PageGraphsSolarCharger", "BroadcastDataMppt"]

FIELD_SPECS: list[dict[str, Any]] = [
    {
        "id": "device_name",
        "area": "Header",
        "uiField": "Device name",
        "screenshotValue": "Solar Charger",
        "description": "Runtime/user/device display name shown in page header.",
        "properties": ["customName"],
        "paths": ["/CustomName", "/Description2"],
        "labels": [],
        "unit": "string",
        "notes": "Runtime data; exact source may be deviceJson.customName, /CustomName, /Description2, or DeviceInfo.",
    },
    {
        "id": "solar_voltage",
        "area": "Status / Solar",
        "uiField": "Solar voltage",
        "screenshotValue": "0.81 V",
        "description": "PV input voltage.",
        "properties": ["pvVoltage"],
        "paths": ["/Pv/V"],
        "labels": ["Solar", "Voltage"],
        "unit": "V",
        "notes": "Per-tracker alternatives /Pv/0..3/V are also present.",
    },
    {
        "id": "solar_current",
        "area": "Status / Solar",
        "uiField": "Solar current",
        "screenshotValue": "0.0 A",
        "description": "PV input current.",
        "properties": ["pvCurrent"],
        "paths": ["/Pv/I"],
        "labels": ["Solar", "Current"],
        "unit": "A",
        "notes": "Per-tracker alternatives /Pv/0..3/I are also present.",
    },
    {
        "id": "solar_power",
        "area": "Status / Solar",
        "uiField": "Solar power",
        "screenshotValue": "0 W",
        "description": "PV charger/input power as displayed in Status.",
        "properties": ["pvPower"],
        "paths": ["/Yield/Power"],
        "labels": ["Solar", "Power"],
        "unit": "W",
        "notes": "Per-tracker alternatives /Pv/0..3/P are also present; /Link/Yield/Power exists for linked setups.",
    },
    {
        "id": "battery_voltage",
        "area": "Status / Battery",
        "uiField": "Battery voltage",
        "screenshotValue": "25.58 V",
        "description": "Battery/DC bus voltage.",
        "properties": ["batteryVoltage"],
        "paths": ["/Dc/0/Voltage"],
        "labels": ["Battery", "Voltage"],
        "unit": "V",
        "notes": "Status page value; trend graph has batteryVoltageVreg separately.",
    },
    {
        "id": "battery_current",
        "area": "Status / Battery",
        "uiField": "Battery current",
        "screenshotValue": "0.00 A",
        "description": "Battery/DC current.",
        "properties": ["batteryCurrent"],
        "paths": ["/Dc/0/Current"],
        "labels": ["Battery", "Current"],
        "unit": "A",
        "notes": "Status page value; trend graph has batteryCurrentVreg separately.",
    },
    {
        "id": "charger_state",
        "area": "Status / Battery",
        "uiField": "Charger state",
        "screenshotValue": "Off",
        "description": "Main charger state enum rendered by SystemState/getStateText.",
        "properties": ["state"],
        "paths": ["/State"],
        "labels": ["State", "Off"],
        "unit": "enum",
        "notes": "Known enum names are in scripts/read-victron-live-values.py; runtime capture needed for exact value.",
    },
    {
        "id": "charger_off_reason",
        "area": "Status / Battery",
        "uiField": "Why is the charger off? / charger off reason",
        "screenshotValue": "Why is the charger off?",
        "description": "Off-reason panel/help text shown when charger is off.",
        "properties": ["deviceOffReason", "offReasonPanel"],
        "paths": ["/DeviceOffReason"],
        "labels": ["Why is the charger off?", "Charger off reason"],
        "unit": "enum/help text",
        "notes": "DeviceOffReasons qmlData contains reason strings #1..#18; numeric mapping still needs runtime confirmation.",
    },
    {
        "id": "load_output_state",
        "area": "Status / Load output",
        "uiField": "Load output state",
        "screenshotValue": "Off",
        "description": "Load-output state enum.",
        "properties": ["loadOutputState"],
        "paths": ["/Load/State"],
        "labels": ["Load output", "State", "Off"],
        "unit": "enum",
        "notes": "Likely 0=Off, 1=On; confirm against runtime value.",
    },
    {
        "id": "load_output_current",
        "area": "Status / Load output",
        "uiField": "Load output current",
        "screenshotValue": "0.0 A",
        "description": "Load-output current.",
        "properties": ["loadOutputCurrent"],
        "paths": ["/Load/I"],
        "labels": ["Load output", "Current"],
        "unit": "A",
        "notes": "BroadcastDataMppt also uses /Load/I.",
    },
    {
        "id": "load_output_power",
        "area": "Status / Load output",
        "uiField": "Load output power",
        "screenshotValue": "0 W",
        "description": "Load-output power shown in Status.",
        "properties": ["loadOutputPower"],
        "paths": ["/Load/V", "/Load/I"],
        "labels": ["Load output", "Power"],
        "unit": "W",
        "notes": "Static QML exposes loadOutputPower plus /Load/V and /Load/I; likely calculated unless a product-specific /Load/P-like path is found.",
    },
    {
        "id": "trends_y_axis_scale",
        "area": "Trends chart",
        "uiField": "Trend chart y-axis kWh labels",
        "screenshotValue": "3.49 kWh, 1.75 kWh",
        "description": "Chart axis scale labels, not standalone battery/load status values.",
        "properties": ["totalYieldToday", "totalLoadToday", "labelBarSeries", "labelSecondBarSeries"],
        "paths": ["/History/Daily/", "/0/Yield", "/0/Consumption"],
        "labels": ["Last 30 days", "Detailed", "Solar", "Load"],
        "unit": "kWh axis",
        "notes": "Values are generated from trend/history data and chart scaling; runtime capture needed to tie to daily history samples.",
    },
    {
        "id": "lifetime_total",
        "area": "Trends / History totals",
        "uiField": "Lifetime total",
        "screenshotValue": "1220 kWh",
        "description": "Total lifetime yield.",
        "properties": ["totalItem"],
        "paths": ["/Yield/System"],
        "labels": ["Lifetime total"],
        "unit": "kWh",
        "notes": "Static QML binds Lifetime total near /Yield/System.",
    },
    {
        "id": "since_reset",
        "area": "Trends / History totals",
        "uiField": "Since reset",
        "screenshotValue": "1220 kWh",
        "description": "User-resettable yield total.",
        "properties": ["sinceClearedItem"],
        "paths": ["/Yield/User"],
        "labels": ["Since reset"],
        "unit": "kWh",
        "notes": "Static QML binds Since reset near /Yield/User.",
    },
]


def load_modules(path: Path) -> dict[str, list[dict[str, Any]]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return {m["module"]: m["strings"] for m in data["modules"]}


def find_hits(modules: dict[str, list[dict[str, Any]]], needles: list[str], module_names: list[str] | None = None) -> list[dict[str, Any]]:
    names = module_names or sorted(modules)
    hits: list[dict[str, Any]] = []
    seen: set[tuple[str, str, str]] = set()
    for module in names:
        for s in modules.get(module, []):
            text = s["text"]
            for needle in needles:
                if text == needle or needle in text:
                    key = (module, s["vma"], text)
                    if key not in seen:
                        hits.append({"module": module, "vma": s["vma"], "offset": s["offset"], "text": text})
                        seen.add(key)
    return hits


def evidence_for_spec(modules: dict[str, list[dict[str, Any]]], spec: dict[str, Any]) -> dict[str, Any]:
    property_hits = find_hits(modules, spec.get("properties", []), PROPERTY_MODULES)
    path_hits = find_hits(modules, spec.get("paths", []), PROPERTY_MODULES)
    label_hits = find_hits(modules, spec.get("labels", []), ["PageSolarCharger", "PageSolarChargerHistory", "SolarChargerHistoryGraphFullSceen", "TrendsSolarCharger", "DeviceOffReasons", "BroadcastDataMppt"])
    confidence = "low"
    if path_hits and property_hits:
        confidence = "medium"
    if path_hits and property_hits and label_hits:
        confidence = "medium-high"
    if spec["id"] in {"lifetime_total", "since_reset"} and path_hits and label_hits:
        confidence = "high-static"
    if spec["id"] in {"trends_y_axis_scale", "device_name", "load_output_power"}:
        confidence = "candidate"
    return {
        "id": spec["id"],
        "area": spec["area"],
        "uiField": spec["uiField"],
        "screenshotValue": spec["screenshotValue"],
        "description": spec["description"],
        "candidateProperties": spec.get("properties", []),
        "candidatePaths": spec.get("paths", []),
        "unit": spec.get("unit", ""),
        "staticConfidence": confidence,
        "needsRuntimeConfirmation": True,
        "notes": spec.get("notes", ""),
        "evidence": {
            "properties": property_hits,
            "paths": path_hits,
            "labels": label_hits,
        },
    }


def extract_off_reasons(modules: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    arr = modules.get("DeviceOffReasons", [])
    reasons: list[dict[str, Any]] = []
    for i, s in enumerate(arr):
        m = re.match(r"#(?P<num>\d+):\s*(?P<name>.+)", s["text"])
        if not m:
            continue
        num = int(m.group("num"))
        name = m.group("name")
        nearby_texts: list[dict[str, Any]] = []
        for n in arr[i + 1 : i + 8]:
            text = n["text"]
            if text.startswith("r") and re.match(r"r\d+(Enabled|Value|Name|Description|Advice|Icon)$", text):
                continue
            if text.startswith("expression for") or text.startswith("qrc:/"):
                continue
            if re.match(r"#\d+:", text):
                break
            if len(text) >= 12:
                nearby_texts.append({"vma": n["vma"], "text": text})
        reasons.append({"valueInLabel": num, "name": name, "labelVma": s["vma"], "nearbyText": nearby_texts})
    return reasons


def collect_paths(modules: dict[str, list[dict[str, Any]]], module_names: list[str]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for module in module_names:
        for s in modules.get(module, []):
            text = s["text"]
            if text.startswith("/"):
                out.append({"module": module, "vma": s["vma"], "text": text})
    return out


def write_markdown(path: Path, result: dict[str, Any]) -> None:
    lines: list[str] = []
    lines.append("# Static UI field candidates")
    lines.append("")
    lines.append("Generated by `scripts/map-qml-fields.py` from `analysis/generated/qmlcache-strings.json`.")
    lines.append("")
    lines.append("These are static candidates, not runtime-confirmed BLE mappings.")
    lines.append("")
    lines.append("## Screenshot field candidates")
    lines.append("")
    lines.append("| Area | UI field | Screenshot value | Candidate path(s) | Property | Unit | Static confidence |")
    lines.append("|---|---|---|---|---|---|---|")
    for f in result["fields"]:
        paths = ", ".join(f["candidatePaths"]) or "-"
        props = ", ".join(f["candidateProperties"]) or "-"
        lines.append(f"| {f['area']} | {f['uiField']} | {f['screenshotValue']} | `{paths}` | `{props}` | {f['unit']} | {f['staticConfidence']} |")
    lines.append("")
    lines.append("## Evidence details")
    for f in result["fields"]:
        lines.append("")
        lines.append(f"### {f['uiField']}")
        lines.append("")
        lines.append(f"- Screenshot value: `{f['screenshotValue']}`")
        lines.append(f"- Candidate paths: {', '.join('`'+p+'`' for p in f['candidatePaths']) or '-'}")
        lines.append(f"- Candidate properties: {', '.join('`'+p+'`' for p in f['candidateProperties']) or '-'}")
        lines.append(f"- Confidence: `{f['staticConfidence']}`")
        lines.append(f"- Notes: {f['notes']}")
        for kind in ["properties", "paths", "labels"]:
            hits = f["evidence"][kind]
            if not hits:
                continue
            lines.append(f"- {kind.title()} evidence:")
            for h in hits[:12]:
                lines.append(f"  - `{h['module']}` `{h['vma']}` `{h['text']}`")
            if len(hits) > 12:
                lines.append(f"  - ... {len(hits) - 12} more")
    lines.append("")
    lines.append("## Device-off reasons")
    lines.append("")
    lines.append("| Value in label | Name | Label VMA | Nearby text |")
    lines.append("|---:|---|---|---|")
    for r in result["offReasons"]:
        nearby = "<br>".join(n["text"] for n in r["nearbyText"][:2])
        lines.append(f"| {r['valueInLabel']} | {r['name']} | `{r['labelVma']}` | {nearby} |")
    lines.append("")
    lines.append("## Trend paths")
    lines.append("")
    for p in result["trendPaths"][:200]:
        lines.append(f"- `{p['module']}` `{p['vma']}` `{p['text']}`")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("qmlcache_json", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--md", type=Path)
    args = ap.parse_args()

    modules = load_modules(args.qmlcache_json)
    fields = [evidence_for_spec(modules, spec) for spec in FIELD_SPECS]
    off_reasons = extract_off_reasons(modules)
    trend_paths = collect_paths(modules, ["VBusItemsSolarCharger", "PageSolarChargerHistory", "SolarChargerHistoryGraphFullSceen", "BroadcastDataMppt"])

    result = {
        "metadata": {
            "source": str(args.qmlcache_json),
            "status": "static-candidates-only",
            "fieldCount": len(fields),
            "offReasonCount": len(off_reasons),
            "trendPathCount": len(trend_paths),
        },
        "fields": fields,
        "offReasons": off_reasons,
        "trendPaths": trend_paths,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
    if args.md:
        args.md.parent.mkdir(parents=True, exist_ok=True)
        write_markdown(args.md, result)
    print(f"fields={len(fields)} offReasons={len(off_reasons)} paths={len(trend_paths)} json={args.out}")
    if args.md:
        print(f"md={args.md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
