//! Map extracted QML strings to reproducible static UI field candidates.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use clap::Args;
use regex::Regex;
use serde_json::{json, Value};

use super::common::write_json;
use crate::{runtime, CliError};

const PROPERTY_MODULES: &[&str] = &[
    "VBusItemsSolarCharger",
    "PageSolarCharger",
    "PageSolarChargerHistory",
    "SolarChargerHistoryGraphFullSceen",
    "TrendsSolarCharger",
    "PageGraphsSolarCharger",
    "BroadcastDataMppt",
];
const LABEL_MODULES: &[&str] = &[
    "PageSolarCharger",
    "PageSolarChargerHistory",
    "SolarChargerHistoryGraphFullSceen",
    "TrendsSolarCharger",
    "DeviceOffReasons",
    "BroadcastDataMppt",
];
const TREND_MODULES: &[&str] = &[
    "VBusItemsSolarCharger",
    "PageSolarChargerHistory",
    "SolarChargerHistoryGraphFullSceen",
    "BroadcastDataMppt",
];

#[derive(Debug, Args)]
pub struct MapQmlFields {
    /// JSON generated by `victron-cli extract-qmlcache`.
    qmlcache_json: PathBuf,
    /// Candidate mapping JSON output.
    #[arg(long)]
    out: PathBuf,
    /// Optional Markdown report.
    #[arg(long)]
    md: Option<PathBuf>,
}

#[derive(Clone, Copy)]
struct Spec {
    id: &'static str,
    area: &'static str,
    field: &'static str,
    screenshot: &'static str,
    description: &'static str,
    properties: &'static [&'static str],
    paths: &'static [&'static str],
    labels: &'static [&'static str],
    unit: &'static str,
    notes: &'static str,
}

const SPECS: &[Spec] = &[
    Spec { id: "device_name", area: "Header", field: "Device name", screenshot: "Solar Charger", description: "Runtime/user/device display name shown in page header.", properties: &["customName"], paths: &["/CustomName", "/Description2"], labels: &[], unit: "string", notes: "Runtime data; exact source may be deviceJson.customName, /CustomName, /Description2, or DeviceInfo." },
    Spec { id: "solar_voltage", area: "Status / Solar", field: "Solar voltage", screenshot: "0.81 V", description: "PV input voltage.", properties: &["pvVoltage"], paths: &["/Pv/V"], labels: &["Solar", "Voltage"], unit: "V", notes: "Per-tracker alternatives /Pv/0..3/V are also present." },
    Spec { id: "solar_current", area: "Status / Solar", field: "Solar current", screenshot: "0.0 A", description: "PV input current.", properties: &["pvCurrent"], paths: &["/Pv/I"], labels: &["Solar", "Current"], unit: "A", notes: "Per-tracker alternatives /Pv/0..3/I are also present." },
    Spec { id: "solar_power", area: "Status / Solar", field: "Solar power", screenshot: "0 W", description: "PV charger/input power as displayed in Status.", properties: &["pvPower"], paths: &["/Yield/Power"], labels: &["Solar", "Power"], unit: "W", notes: "Per-tracker alternatives /Pv/0..3/P are also present; /Link/Yield/Power exists for linked setups." },
    Spec { id: "battery_voltage", area: "Status / Battery", field: "Battery voltage", screenshot: "25.58 V", description: "Battery/DC bus voltage.", properties: &["batteryVoltage"], paths: &["/Dc/0/Voltage"], labels: &["Battery", "Voltage"], unit: "V", notes: "Status page value; trend graph has batteryVoltageVreg separately." },
    Spec { id: "battery_current", area: "Status / Battery", field: "Battery current", screenshot: "0.00 A", description: "Battery/DC current.", properties: &["batteryCurrent"], paths: &["/Dc/0/Current"], labels: &["Battery", "Current"], unit: "A", notes: "Status page value; trend graph has batteryCurrentVreg separately." },
    Spec { id: "charger_state", area: "Status / Battery", field: "Charger state", screenshot: "Off", description: "Main charger state enum rendered by SystemState/getStateText.", properties: &["state"], paths: &["/State"], labels: &["State", "Off"], unit: "enum", notes: "Runtime capture is required for the exact value." },
    Spec { id: "charger_off_reason", area: "Status / Battery", field: "Why is the charger off? / charger off reason", screenshot: "Why is the charger off?", description: "Off-reason panel/help text shown when charger is off.", properties: &["deviceOffReason", "offReasonPanel"], paths: &["/DeviceOffReason"], labels: &["Why is the charger off?", "Charger off reason"], unit: "enum/help text", notes: "DeviceOffReasons contains reason strings; numeric mapping needs runtime confirmation." },
    Spec { id: "load_output_state", area: "Status / Load output", field: "Load output state", screenshot: "Off", description: "Load-output state enum.", properties: &["loadOutputState"], paths: &["/Load/State"], labels: &["Load output", "State", "Off"], unit: "enum", notes: "Likely 0=Off, 1=On; confirm against runtime value." },
    Spec { id: "load_output_current", area: "Status / Load output", field: "Load output current", screenshot: "0.0 A", description: "Load-output current.", properties: &["loadOutputCurrent"], paths: &["/Load/I"], labels: &["Load output", "Current"], unit: "A", notes: "BroadcastDataMppt also uses /Load/I." },
    Spec { id: "load_output_power", area: "Status / Load output", field: "Load output power", screenshot: "0 W", description: "Load-output power shown in Status.", properties: &["loadOutputPower"], paths: &["/Load/V", "/Load/I"], labels: &["Load output", "Power"], unit: "W", notes: "Likely calculated unless a product-specific power path is found." },
    Spec { id: "trends_y_axis_scale", area: "Trends chart", field: "Trend chart y-axis kWh labels", screenshot: "3.49 kWh, 1.75 kWh", description: "Chart axis scale labels, not standalone status values.", properties: &["totalYieldToday", "totalLoadToday", "labelBarSeries", "labelSecondBarSeries"], paths: &["/History/Daily/", "/0/Yield", "/0/Consumption"], labels: &["Last 30 days", "Detailed", "Solar", "Load"], unit: "kWh axis", notes: "Generated from history data and chart scaling; runtime confirmation required." },
    Spec { id: "lifetime_total", area: "Trends / History totals", field: "Lifetime total", screenshot: "1220 kWh", description: "Total lifetime yield.", properties: &["totalItem"], paths: &["/Yield/System"], labels: &["Lifetime total"], unit: "kWh", notes: "Static QML binds Lifetime total near /Yield/System." },
    Spec { id: "since_reset", area: "Trends / History totals", field: "Since reset", screenshot: "1220 kWh", description: "User-resettable yield total.", properties: &["sinceClearedItem"], paths: &["/Yield/User"], labels: &["Since reset"], unit: "kWh", notes: "Static QML binds Since reset near /Yield/User." },
];

impl MapQmlFields {
    pub fn run(&self) -> Result<(), CliError> {
        let text = std::fs::read_to_string(&self.qmlcache_json)
            .map_err(|error| runtime(format!("failed to read QML cache JSON: {error}")))?;
        let source: Value = serde_json::from_str(&text)
            .map_err(|error| runtime(format!("invalid QML cache JSON: {error}")))?;
        let modules = load_modules(&source)?;
        let fields = SPECS
            .iter()
            .map(|spec| evidence_for_spec(&modules, spec))
            .collect::<Vec<_>>();
        let off_reasons = extract_off_reasons(&modules);
        let trend_paths = collect_paths(&modules, TREND_MODULES);
        let result = json!({
            "metadata": {
                "source": self.qmlcache_json,
                "status": "static-candidates-only",
                "fieldCount": fields.len(),
                "offReasonCount": off_reasons.len(),
                "trendPathCount": trend_paths.len(),
            },
            "fields": fields,
            "offReasons": off_reasons,
            "trendPaths": trend_paths,
        });
        write_json(&result, &self.out)?;
        if let Some(path) = &self.md {
            write_markdown(path, &result)?;
        }
        eprintln!(
            "fields={} offReasons={} paths={} json={}",
            result["metadata"]["fieldCount"],
            result["metadata"]["offReasonCount"],
            result["metadata"]["trendPathCount"],
            self.out.display()
        );
        Ok(())
    }
}

type Modules = BTreeMap<String, Vec<Value>>;

fn load_modules(source: &Value) -> Result<Modules, CliError> {
    let modules = source["modules"]
        .as_array()
        .ok_or_else(|| runtime("QML cache JSON lacks modules array"))?;
    modules
        .iter()
        .map(|module| {
            let name = module["module"]
                .as_str()
                .ok_or_else(|| runtime("QML module lacks name"))?;
            let strings = module["strings"]
                .as_array()
                .ok_or_else(|| runtime("QML module lacks strings array"))?;
            Ok((name.to_string(), strings.clone()))
        })
        .collect()
}

fn find_hits(modules: &Modules, needles: &[&str], names: &[&str]) -> Vec<Value> {
    let mut seen = BTreeSet::new();
    let mut hits = Vec::new();
    for name in names {
        for string in modules.get(*name).into_iter().flatten() {
            let Some(text) = string["text"].as_str() else {
                continue;
            };
            if !needles
                .iter()
                .any(|needle| text == *needle || text.contains(needle))
            {
                continue;
            }
            let vma = string["vma"].as_str().unwrap_or_default();
            if seen.insert(((*name).to_string(), vma.to_string(), text.to_string())) {
                hits.push(json!({
                    "module": name,
                    "vma": vma,
                    "offset": string["offset"],
                    "text": text,
                }));
            }
        }
    }
    hits
}

fn evidence_for_spec(modules: &Modules, spec: &Spec) -> Value {
    let properties = find_hits(modules, spec.properties, PROPERTY_MODULES);
    let paths = find_hits(modules, spec.paths, PROPERTY_MODULES);
    let labels = find_hits(modules, spec.labels, LABEL_MODULES);
    let mut confidence = if !paths.is_empty() && !properties.is_empty() {
        "medium"
    } else {
        "low"
    };
    if !paths.is_empty() && !properties.is_empty() && !labels.is_empty() {
        confidence = "medium-high";
    }
    if matches!(spec.id, "lifetime_total" | "since_reset")
        && !paths.is_empty()
        && !labels.is_empty()
    {
        confidence = "high-static";
    }
    if matches!(
        spec.id,
        "trends_y_axis_scale" | "device_name" | "load_output_power"
    ) {
        confidence = "candidate";
    }
    json!({
        "id": spec.id,
        "area": spec.area,
        "uiField": spec.field,
        "screenshotValue": spec.screenshot,
        "description": spec.description,
        "candidateProperties": spec.properties,
        "candidatePaths": spec.paths,
        "unit": spec.unit,
        "staticConfidence": confidence,
        "needsRuntimeConfirmation": true,
        "notes": spec.notes,
        "evidence": {"properties": properties, "paths": paths, "labels": labels},
    })
}

fn extract_off_reasons(modules: &Modules) -> Vec<Value> {
    let pattern = Regex::new(r"^#(\d+):\s*(.+)$").expect("static regex");
    let property =
        Regex::new(r"^r\d+(Enabled|Value|Name|Description|Advice|Icon)$").expect("static regex");
    let strings = modules
        .get("DeviceOffReasons")
        .map(Vec::as_slice)
        .unwrap_or(&[]);
    let mut reasons = Vec::new();
    for (index, string) in strings.iter().enumerate() {
        let Some(text) = string["text"].as_str() else {
            continue;
        };
        let Some(captures) = pattern.captures(text) else {
            continue;
        };
        let mut nearby = Vec::new();
        for candidate in strings.iter().skip(index + 1).take(7) {
            let text = candidate["text"].as_str().unwrap_or_default();
            if pattern.is_match(text) {
                break;
            }
            if property.is_match(text)
                || text.starts_with("expression for")
                || text.starts_with("qrc:/")
                || text.len() < 12
            {
                continue;
            }
            nearby.push(json!({"vma": candidate["vma"], "text": text}));
        }
        reasons.push(json!({
            "valueInLabel": captures[1].parse::<u64>().unwrap_or_default(),
            "name": &captures[2],
            "labelVma": string["vma"],
            "nearbyText": nearby,
        }));
    }
    reasons
}

fn collect_paths(modules: &Modules, names: &[&str]) -> Vec<Value> {
    let mut paths = Vec::new();
    for name in names {
        for string in modules.get(*name).into_iter().flatten() {
            let text = string["text"].as_str().unwrap_or_default();
            if text.starts_with('/') {
                paths.push(json!({"module": name, "vma": string["vma"], "text": text}));
            }
        }
    }
    paths
}

fn write_markdown(path: &Path, result: &Value) -> Result<(), CliError> {
    let mut lines = vec![
        "# Static UI field candidates".to_string(),
        String::new(),
        "Generated by `victron-cli map-qml-fields`.".to_string(),
        String::new(),
        "These are static candidates, not runtime-confirmed BLE mappings.".to_string(),
        String::new(),
        "## Screenshot field candidates".to_string(),
        String::new(),
        "| Area | UI field | Screenshot value | Candidate path(s) | Property | Unit | Static confidence |".to_string(),
        "|---|---|---|---|---|---|---|".to_string(),
    ];
    for field in result["fields"].as_array().into_iter().flatten() {
        lines.push(format!(
            "| {} | {} | {} | `{}` | `{}` | {} | {} |",
            field["area"].as_str().unwrap_or_default(),
            field["uiField"].as_str().unwrap_or_default(),
            field["screenshotValue"].as_str().unwrap_or_default(),
            join_strings(&field["candidatePaths"]),
            join_strings(&field["candidateProperties"]),
            field["unit"].as_str().unwrap_or_default(),
            field["staticConfidence"].as_str().unwrap_or_default(),
        ));
    }
    lines.extend([String::new(), "## Evidence details".to_string()]);
    for field in result["fields"].as_array().into_iter().flatten() {
        lines.extend([
            String::new(),
            format!("### {}", field["uiField"].as_str().unwrap_or_default()),
            String::new(),
            format!(
                "- Screenshot value: `{}`",
                field["screenshotValue"].as_str().unwrap_or_default()
            ),
            format!(
                "- Candidate paths: {}",
                markdown_code_list(&field["candidatePaths"])
            ),
            format!(
                "- Candidate properties: {}",
                markdown_code_list(&field["candidateProperties"])
            ),
            format!(
                "- Confidence: `{}`",
                field["staticConfidence"].as_str().unwrap_or_default()
            ),
            format!("- Notes: {}", field["notes"].as_str().unwrap_or_default()),
        ]);
        for kind in ["properties", "paths", "labels"] {
            let Some(hits) = field["evidence"][kind].as_array() else {
                continue;
            };
            if hits.is_empty() {
                continue;
            }
            lines.push(format!("- {kind} evidence:"));
            for hit in hits.iter().take(12) {
                lines.push(format!(
                    "  - `{}` `{}` `{}`",
                    hit["module"].as_str().unwrap_or_default(),
                    hit["vma"].as_str().unwrap_or_default(),
                    hit["text"].as_str().unwrap_or_default()
                ));
            }
            if hits.len() > 12 {
                lines.push(format!("  - ... {} more", hits.len() - 12));
            }
        }
    }
    lines.extend([
        String::new(),
        "## Device-off reasons".to_string(),
        String::new(),
        "| Value in label | Name | Label VMA | Nearby text |".to_string(),
        "|---:|---|---|---|".to_string(),
    ]);
    for reason in result["offReasons"].as_array().into_iter().flatten() {
        let nearby = reason["nearbyText"]
            .as_array()
            .into_iter()
            .flatten()
            .take(2)
            .filter_map(|item| item["text"].as_str())
            .collect::<Vec<_>>()
            .join("<br>");
        lines.push(format!(
            "| {} | {} | `{}` | {} |",
            reason["valueInLabel"],
            reason["name"].as_str().unwrap_or_default(),
            reason["labelVma"].as_str().unwrap_or_default(),
            nearby
        ));
    }
    lines.extend([String::new(), "## Trend paths".to_string(), String::new()]);
    for item in result["trendPaths"]
        .as_array()
        .into_iter()
        .flatten()
        .take(200)
    {
        lines.push(format!(
            "- `{}` `{}` `{}`",
            item["module"].as_str().unwrap_or_default(),
            item["vma"].as_str().unwrap_or_default(),
            item["text"].as_str().unwrap_or_default()
        ));
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|error| runtime(format!("failed to create output directory: {error}")))?;
    }
    std::fs::write(path, lines.join("\n") + "\n")
        .map_err(|error| runtime(format!("failed to write Markdown: {error}")))
}

fn join_strings(value: &Value) -> String {
    value
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<Vec<_>>()
        .join(", ")
}

fn markdown_code_list(value: &Value) -> String {
    let values = value
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(|value| format!("`{value}`"))
        .collect::<Vec<_>>();
    if values.is_empty() {
        "-".to_string()
    } else {
        values.join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn static_spec_count_stays_complete() {
        assert_eq!(SPECS.len(), 14);
    }

    #[test]
    fn evidence_confidence_uses_all_three_evidence_classes() {
        let mut modules = Modules::new();
        modules.insert(
            "PageSolarCharger".into(),
            vec![
                json!({"text": "pvVoltage", "vma": "0x1", "offset": 0}),
                json!({"text": "/Pv/V", "vma": "0x2", "offset": 2}),
                json!({"text": "Solar Voltage", "vma": "0x3", "offset": 4}),
            ],
        );
        let value = evidence_for_spec(&modules, &SPECS[1]);
        assert_eq!(value["staticConfidence"], "medium-high");
    }
}
